[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'forge-cache'
remappings = [
    "@blockswaplab/stakehouse-contract-interfaces/=lib/stakehouse-contract-interfaces"
]
